apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::364649219390:role/eksctl-simple-jwt-api-v2-nodegrou-NodeInstanceRole-14WDQMAI1ZJB4
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-17T17:42:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1809"
  uid: 12716901-f3b3-4dd7-b2f4-c9dc7dd2c36f
