apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::364649219390:role/eksctl-simple-jwt-api-v3-nodegrou-NodeInstanceRole-1GLHSO2XERJGH
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::364649219390:role/UdacityFlaskDeployCBKubectlRole2
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-18T08:24:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1503"
  uid: 8eb24e0c-e521-41ee-ae24-31ba20ae59c1
